[WIP] Replacing `ValueError` in `sourmash_tst_utils.runscript(...)` with a custom exception
sourmash-bio/sourmash pull request #1621
Opened 2021-06-21 20:49 UTC by keyabarve

Fixes #1611 

TODO: 
- define a new exception class, SourmashCommandFailed, in sourmash_tst_utils.py; it should inherit from Exception;
- change the behavior in sourmash_tst_utils.py
- fix all of the tests that use with pytest.raises(ValueError) to instead use with pytest.raises(SourmashCommandFailed)

2021-06-24 04:10 UTC, keyabarve commented
@ctb I have a couple of questions: 
- Should this class be defined in `sourmash_tst_utils.py`? 
- If so, what does this mean: "change the behavior in `sourmash_tst_utils.py`"?
- What does this mean: " it should inherit from `Exception`"?

2021-06-24 12:33 UTC, ctb commented
> @ctb I have a couple of questions:
> 
>     * Should this class be defined in `sourmash_tst_utils.py`?

sure!

>     * If so, what does this mean: "change the behavior in `sourmash_tst_utils.py`"?

The new exception should be used in the code to signal that the script has exited with an error.

>     * What does this mean: " it should inherit from `Exception`"?

Exceptions are part of a class hierarchy in Python, so any new exception needs to have a base class. This affects how you catch and handle exceptions: If, for example, you defined a new exception as a subclass of `ValueError`, then `try: ... except ValueError: ...` would catch the new exception as well as any other `ValueError`.

In this case, I think the new exception should be a direct subclass of `Exception`, to reduce confusion about its connection with other exceptions used in soumash.

2021-07-20 00:46 UTC, keyabarve commented
@ctb Could you provide some hints on how and where to get started?

2021-07-20 14:10 UTC, ctb commented
hi @keyabarve I think your list of TODO items in the comment for this PR is a decent checklist. I've given you some example code over in https://github.com/sourmash-bio/sourmash/pull/1679.

2021-07-29 06:22 UTC, keyabarve commented
@ctb I have added the `SourmashCommandFailed` class and just the `_init(..)` function to it. I have used `class SourmashError(Exception)` in `src/sourmash/exceptions.py` as a reference.

2021-08-05 20:02 UTC, keyabarve commented
I have written the `SourmashCommandFailed` class in `tests/sourmash_tst_utils.py`, and I would like you to review it and tell me if I should make any changes. I also wanted to know if I should start changing all the tests where `ValueError` is raised and for this, if we should create a new, repeating issue, start working on this in a new branch and PR, and close this current branch and PR.

2021-08-05 22:16 UTC, keyabarve commented
In some of the tests, where I’ve replaced `with pytest.raises(ValueError) as exc:` with the command `with pytest.raises(utils.SourmashCommandFailed) as exc:` and the assert statement outside this block is in this format: `assert "..." in str(exc.value)`, this is an example of the error that I’m getting:
```E       AssertionError: assert 'taxonomy table already exists' in ''
E        +  where '' = str(SourmashCommandFailed())
E        +    where SourmashCommandFailed() = <ExceptionInfo SourmashCommandFailed() tblen=2>.value```
If I change the assert statement to: `assert "..." in c.last_result.err`, the tests pass. I was wondering if it would be okay to change the assert statement in this manner.

2021-08-06 10:59 UTC, ctb commented
hi keya, ideally, you would need to only change the name of the exception, and nothing else.

In this case, it looks like you are not executing the parent class constructor properly and so the new exception class is not storing the message string. You definitely want the exception class to store the message string, in general!

To fix this, you could either call `Exception.__init__` with the full set of arguments passed to `SourmashCommandFailed.__init__`, or use `super` for single inheritance, as per [this article](https://realpython.com/python-super/.

Note also that you can do a `from sourmash_tst_utils import SourmashCommandFailed` to avoid the `utils.` prefix if you like.

2021-08-06 19:12 UTC, keyabarve commented
> hi keya, ideally, you would need to only change the name of the exception, and nothing else.
> 
> In this case, it looks like you are not executing the parent class constructor properly and so the new exception class is not storing the message string. You definitely want the exception class to store the message string, in general!
> 
> To fix this, you could either call `Exception.__init__` with the full set of arguments passed to `SourmashCommandFailed.__init__`, or use `super` for single inheritance, as per [this article](https://realpython.com/python-super/.
> 
Okay, thanks I'll take a look at this.

> Note also that you can do a `from sourmash_tst_utils import SourmashCommandFailed` to avoid the `utils.` prefix if you like.
>
Sure, I'll do that.

2021-08-07 03:06 UTC, keyabarve commented
@ctb I have made all the changes you requested and the tests now pass. This is ready for review.

2021-08-07 13:41 UTC, ctb requested changes
one minor change ;)

2021-08-07 13:41 UTC, ctb commented on tests/sourmash_tst_utils.py
> +            # raise ValueError(self)
please remove commented out line

2021-08-07 13:41 UTC, ctb commented
reminder - please change the title to MRG.

2021-08-07 19:54 UTC, keyabarve commented
@ctb Please review.

2021-08-08 13:47 UTC, ctb commented
hi keya, a test is failing because you merged from `latest` and a new test from that merge used the old `ValueError`. Could you please fix?

2021-08-09 22:07 UTC, keyabarve commented
> hi keya, a test is failing because you merged from `latest` and a new test from that merge used the old `ValueError`. Could you please fix?
>
Alright!

2021-08-09 22:35 UTC, keyabarve commented
@ctb Please review.

2021-08-10 00:09 UTC, ctb approved these changes

2021-08-10 00:09 UTC, merged

2021-08-10 00:09 UTC, ctb commented
🎉