[WIP] Doing bounds checking on `--num` via command line
sourmash-bio/sourmash pull request #1688
Opened 2021-07-27 19:39 UTC by keyabarve

Fixes #1243

TODO:
Add checks for the values of num. num values should always be > 0. if they are unreasonable, say > 50,000 or < 50, we should emit a warning.

2021-07-28 06:17 UTC, keyabarve commented
@ctb I have written the function in `src/sourmash/cli/utils.py` similar to the function I had written for `--scaled`. I have used the `subparser.add_argument` code block in `src/sourmash/cli/sig/downsample.py` as reference and changed the code in this file accordingly. I'm a little confused about what needs to be done with the code in `src/sourmash/cli/compute.py` and `src/sourmash/cli/watch.py` because this is different from the code in `src/sourmash/cli/sig/downsample.py` in the sense that this involved `--num-hashes` instead of `--num`.

2021-07-28 13:05 UTC, ctb commented
You could do a couple of things - you could add some parameters to the function to set the argument name, or you could add aliases so that `--num` and `--num-hashes` both work, or you could use the `check_num_bounds` function directly in the various files rather than having the `add_num_arg` function.

2021-07-28 19:26 UTC, keyabarve commented
What do you mean by: "you could add aliases so that `--num` and `--num-hashes` both work"?

2021-07-29 02:15 UTC, keyabarve commented
@ctb What does the `sketch_args.add_argument(...)` in `src/sourmash/cli/compute.py` mean? How is it different from `subparser.add_argument(...)`? Will I have to write my code differently for this file specifically / are there any special things that need to be considered while replacing the code block in this file?

2021-07-29 04:35 UTC, keyabarve commented
@ctb I added a few things to the `add_num_arg` function and all the tests now pass. Please review.

2021-07-29 10:59 UTC, ctb commented
if it's ready for review and merge, please rename it to MRG, thx

2021-07-29 11:29 UTC, ctb commented
> @ctb What does the `sketch_args.add_argument(...)` in `src/sourmash/cli/compute.py` mean? How is it different from `subparser.add_argument(...)`? Will I have to write my code differently for this file specifically / are there any special things that need to be considered while replacing the code block in this file?

I don't know offhand and don't have time to dig into it. If you're unsure and don't want to look into it yourself, you can just leave it alone.

2021-07-29 11:33 UTC, ctb commented
> What do you mean by: "you could add aliases so that `--num` and `--num-hashes` both work"?

see https://stackoverflow.com/questions/50896992/argparse-add-argument-alias - the idea is that you could support both styles of argument for each command.

So I could imagine adding `--num` as an alias for `--num-hashes` where the command supports the latter already, and `--num-hashes` as an alias for `--num` where the command supports `--num` already. (You have to do this in order to keep the same CLI behavior working, which we do within major versions of sourmash;  it's fine to add new behavior tho, as long as the old behavior keeps working.)

In practice, if a command supports `--num-hashes`, it will support `--num` because (as I only recently learned myself :) argparse will do substring matching. But I don't think it hurts to explicitly add `--num` as an alias to commands that support `--num-hashing` already.

2021-07-29 17:36 UTC, keyabarve commented
> > @ctb What does the `sketch_args.add_argument(...)` in `src/sourmash/cli/compute.py` mean? How is it different from `subparser.add_argument(...)`? Will I have to write my code differently for this file specifically / are there any special things that need to be considered while replacing the code block in this file?
> 
> I don't know offhand and don't have time to dig into it. If you're unsure and don't want to look into it yourself, you can just leave it alone.
>
I'll look into it for a while, but if I'm not being able to find anything useful, I'll leave it alone.

2021-07-29 17:41 UTC, keyabarve commented
@ctb I haven't written any tests to test the function I wrote. I'll write some tests in `tests/test_sourmash.py`, using the tests I wrote for `--scaled` as a reference and then put it up for review and merge!

2021-07-29 18:35 UTC, keyabarve commented
In this issue, I added the function in `utils.py` and modified `compute.py`, `downsample.py` and `watch.py`.
- Do I need to change any other files?
- When I write tests to check the functionality, which commands should I be testing for?
- Since I changed `sourmash compute` to `sourmash sketch` in almost all the places in the other issue I was working on, do I still need to test the `--num bounds` for `compute`?
- I’ll surely write some tests for the `watch` command. I’m also not sure how to test for the changes in `downsample.py`.
- Should I also test for other commands such as `gather`, `search`?

2021-07-29 18:50 UTC, ctb commented
> In this issue, I added the function in `utils.py` and modified `compute.py`, `downsample.py` and `watch.py`.
> 
>     * Do I need to change any other files?

I don't know; do your current changes address the issue?

>     * When I write tests to check the functionality, which commands should I be testing for?

You should cover all of the code that you changed with tests, as well as providing tests to make sure that the original issue was resolved.

>     * Since I changed `sourmash compute` to `sourmash sketch` in almost all the places in the other issue I was working on, do I still need to test the `--num bounds` for `compute`?

That's a good question. Please note it in the top of the PR and it can be part of the review.

>     * I’ll surely write some tests for the `watch` command. I’m also not sure how to test for the changes in `downsample.py`.

There are many existing tests for downsample, so you might consider adapting those.

>     * Should I also test for other commands such as `gather`, `search`?

You should cover all of the code that you changed with tests, as well as providing tests to make sure that the original issue was resolved.

2021-07-29 19:03 UTC, keyabarve commented
> > In this issue, I added the function in `utils.py` and modified `compute.py`, `downsample.py` and `watch.py`.
> > ```
> > * Do I need to change any other files?
> > ```
> 
> I don't know; do your current changes address the issue?
> 
I don't think so.
> > ```
> > * When I write tests to check the functionality, which commands should I be testing for?
> > ```
> 
> You should cover all of the code that you changed with tests, as well as providing tests to make sure that the original issue was resolved.
> 
Okay.
> > ```
> > * Since I changed `sourmash compute` to `sourmash sketch` in almost all the places in the other issue I was working on, do I still need to test the `--num bounds` for `compute`?
> > ```
> 
> That's a good question. Please note it in the top of the PR and it can be part of the review.
> 
Sure.
> > ```
> > * I’ll surely write some tests for the `watch` command. I’m also not sure how to test for the changes in `downsample.py`.
> > ```
> 
> There are many existing tests for downsample, so you might consider adapting those.
> 
Alright.
> > ```
> > * Should I also test for other commands such as `gather`, `search`?
> > ```
> 
> You should cover all of the code that you changed with tests, as well as providing tests to make sure that the original issue was resolved.
>
Oh okay.

2021-08-05 19:58 UTC, keyabarve commented
I have a few questions/comments:
- I have changed `args.num` to `args.num_hashes` in the `downsample` function of `src/sourmash/sig/__main__.py`. 
- I also wrote tests in `tests/test_sourmash.py` for the `watch` command. 
- Since I have changed `compute` to `sketch` in most of the places in `tests/test_sourmash.py`, I was wondering whether or not I should write the tests for the `compute` command. 
- If so, then should I write it in `tests/test_sourmash_compute.py`? 
- I also wanted to know if it would be okay to write the tests for the `downsample` command in `tests/test_cmd_signature.py`?

2021-08-06 11:03 UTC, ctb commented on src/sourmash/cli/utils.py
> +        raise argparse.ArgumentTypeError(f"ERROR: --num value must be positive")
this should be `--num-hashes`, right?

2021-08-06 11:07 UTC, ctb commented
> I have a few questions/comments:
> 
>     * Since I have changed `compute` to `sketch` in most of the places in `tests/test_sourmash.py`, I was wondering whether or not I should write the tests for the `compute` command.

I think it would be good to write one test, to make sure the new code is actually being used; but since `compute` is being removed in 5.0, you don't need to test it as thoroughly as code that is remaining.

>     * I also wanted to know if it would be okay to write the tests for the `downsample` command in `tests/test_cmd_signature.py`?

Please write the tests wherever you think best, and if you think they could go in multiple places, indicate that in the PR description as a question you have, together with the list of potential locations and why you think they might fit there better than where you put them. Then the code reviewer can address it in their review.

2021-08-06 19:07 UTC, keyabarve commented on src/sourmash/cli/utils.py
> +        raise argparse.ArgumentTypeError(f"ERROR: --num value must be positive")
Oh right, I'll change that.

2021-08-06 19:08 UTC, keyabarve commented
> > I have a few questions/comments:
> > ```
> > * Since I have changed `compute` to `sketch` in most of the places in `tests/test_sourmash.py`, I was wondering whether or not I should write the tests for the `compute` command.
> > ```
> 
> I think it would be good to write one test, to make sure the new code is actually being used; but since `compute` is being removed in 5.0, you don't need to test it as thoroughly as code that is remaining.
> 
Alright!
> > ```
> > * I also wanted to know if it would be okay to write the tests for the `downsample` command in `tests/test_cmd_signature.py`?
> > ```
> 
> Please write the tests wherever you think best, and if you think they could go in multiple places, indicate that in the PR description as a question you have, together with the list of potential locations and why you think they might fit there better than where you put them. Then the code reviewer can address it in their review.
>
Okay!

2021-08-07 02:55 UTC, keyabarve commented
@ctb This is ready for review.

2021-08-07 13:44 UTC, ctb requested changes
I did a preliminary review and noticed some leftover comments that should be removed.

(I would like to revisit this later to do a larger review, might take me a bit of time.)

2021-08-07 13:44 UTC, ctb commented on src/sourmash/cli/compute.py
> +    # sketch_args.add_argument(
please remove

2021-08-07 18:59 UTC, keyabarve commented on src/sourmash/cli/compute.py
> +    # sketch_args.add_argument(
Alright!

2021-08-08 02:14 UTC, keyabarve commented
@ctb Please review.

2021-08-08 14:08 UTC, ctb requested changes
One minor thing to be cleaned up, otherwise looks good!

2021-08-08 14:08 UTC, ctb commented on src/sourmash/cli/sig/downsample.py
> +from sourmash.cli.utils import (add_moltype_args, add_ksize_arg, add_num_arg,
duplicate import of `add_num_arg` here - pls remove

2021-08-08 14:08 UTC, ctb commented
(oh, and you should of course update from latest too :)

2021-08-09 22:11 UTC, keyabarve commented
> (oh, and you should of course update from latest too :)
>
Yes, I'll do that!

2021-08-09 22:39 UTC, keyabarve commented
@ctb Please review.

2021-08-10 00:08 UTC, ctb approved these changes

2021-08-10 00:08 UTC, merged

2021-08-10 00:08 UTC, ctb commented
thank you!