[WIP] Changing `sourmash compute` to `sourmash sketch` in test files
sourmash-bio/sourmash pull request #1712
Opened 2021-08-11 20:42 UTC by keyabarve

Fixes #1710

Replace `compute` with `sketch` in:
- `tests/test_cmd_signature.py`
- `tests/test_lca.py`
- `tests/test_minhash.py`

2021-08-12 03:33 UTC, keyabarve commented
@ctb One test from `tests/test_cmd_signature.py` is failing. This is the error message:
```
>           raise SourmashCommandFailed(self.last_result.err)

E           == This is sourmash version 4.1.2.dev6+g87a908c.d20210609. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==
E           
E           Traceback (most recent call last):
E             File "/Users/keya/sourmash/tests/sourmash_tst_utils.py", line 105, in runscript
E               status = _runscript(scriptname)
E             File "/Users/keya/sourmash/tests/sourmash_tst_utils.py", line 47, in _runscript
E               pkg_resources.load_entry_point("sourmash", 'console_scripts', scriptname)()
E             File "/Users/keya/sourmash/src/sourmash/__main__.py", line 13, in main
E               return mainmethod(args)
E             File "/Users/keya/sourmash/src/sourmash/cli/sketch/translate.py", line 97, in main
E               return sourmash.command_sketch.translate(args)
E             File "/Users/keya/sourmash/src/sourmash/command_sketch.py", line 259, in translate
E               raise ValueError("cannot set both --dayhoff and --hp")
E           ValueError: cannot set both --dayhoff and --hp

tests/sourmash_tst_utils.py:195: SourmashCommandFailed
```

2021-08-12 12:44 UTC, ctb commented
it would be helpful to know the test name...

in re
>ValueError: cannot set both --dayhoff and --hp

I don't think you can create signatures like this with sourmash sketch,
so just note that this test can't be updated to use sketch in the PR
description, and we'll create a new issue to tackle it when we merge
the PR.

2021-08-12 20:21 UTC, keyabarve commented
> it would be helpful to know the test name... in re
> ValueError: cannot set both --dayhoff and --hp
>
This is the test: `tests/test_cmd_signature.py::test_sig_describe_1_hp`

> I don't think you can create signatures like this with sourmash sketch, so just note that this test can't be updated to use sketch in the PR description, and we'll create a new issue to tackle it when we merge the PR.
>
Alright!

2021-08-12 20:56 UTC, keyabarve commented
@ctb Ready for review and merge!

2021-08-13 12:16 UTC, ctb requested changes
looks good! just one thing to change.

please also change title to MRG

2021-08-13 12:16 UTC, ctb commented on tests/test_cmd_signature.py
> +                   testdata)
unintentional change

2021-08-13 23:46 UTC, keyabarve commented
@ctb Ready for review and merge!

2021-08-14 12:32 UTC, ctb approved these changes

2021-08-14 18:47 UTC, keyabarve commented
Should I merge this?

2021-08-15 00:34 UTC, ctb commented
sure!

2021-08-15 00:34 UTC, merged